org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8 -Dorg.sqlite.tmpdir=C:/PROJET~1/LEDGER~1/build/tmp/sqlite -Djava.io.tmpdir=C:/PROJET~1/LEDGER~1/build/tmp
systemProp.org.sqlite.tmpdir=C:/PROJET~1/LEDGER~1/build/tmp/sqlite
systemProp.java.io.tmpdir=C:/PROJET~1/LEDGER~1/build/tmp
android.suppressUnsupportedCompileSdk=35
kotlin.code.style=official
android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.native.cocoapods.generate.wrapper=true
