org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8 -Djava.io.tmpdir=C:/Users/MouraD/AppData/Local/Temp -Dorg.sqlite.tmpdir=C:/Users/MouraD/AppData/Local/Temp
systemProp.org.sqlite.tmpdir=C:/Users/MouraD/AppData/Local/Temp
systemProp.java.io.tmpdir=C:/Users/MouraD/AppData/Local/Temp
android.suppressUnsupportedCompileSdk=35
kotlin.code.style=official
android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.native.cocoapods.generate.wrapper=true
