org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8 -Dorg.sqlite.tmpdir=C:/Users/MouraD/AppData/Local/Temp/ledgerhub-sqlite -Djava.io.tmpdir=C:/Users/MouraD/AppData/Local/Temp/ledgerhub-sqlite
systemProp.org.sqlite.tmpdir=C:/Users/MouraD/AppData/Local/Temp/ledgerhub-sqlite
systemProp.java.io.tmpdir=C:/Users/MouraD/AppData/Local/Temp/ledgerhub-sqlite
android.suppressUnsupportedCompileSdk=35
kotlin.code.style=official
android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.native.cocoapods.generate.wrapper=true
